<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9buGX8o\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9buGX8o/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9buGX8o.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9buGX8o\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container9buGX8o\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '9buGX8o',
    'container.build_id' => '3cecd6a2',
    'container.build_time' => 1650351138,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9buGX8o');
